#!/bin/bash
# core/hooks/pre-tool-use/protect-files.sh
# Korumalı dosyaların Claude tarafından düzenlenmesini engeller.
# Claude'a neden engellendiğini bildirir.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# Dosya yolu yoksa geç
if [ -z "$FILE_PATH" ]; then
  exit 0
fi

PROTECTED_PATTERNS=(
  # Xcode proje dosyaları — Xcode tarafından yönetilir, elle düzenleme proje bozar
  ".pbxproj"
  ".xcworkspace"
  "xcuserdata/"
  "DerivedData/"

  # Uygulama meta/yetki — Xcode arayüzünden düzenlenmeli, direkt edit tehlikeli
  "Info.plist"
  ".entitlements"

  # Asset catalog metadata — Xcode asset editöründen yönetilmeli
  "Assets.xcassets/Contents.json"

  # Lock dosyaları — otomatik oluşturulur, elle düzenlenmez
  "Package.resolved"
  "Podfile.lock"

  # Hassas yapılandırma — API key, gizli bilgi içerir
  "GoogleService-Info.plist"
  "Secrets.swift"
  ".env"
  ".env.local"
  ".env.production"

  # Binary sertifika dosyaları — edit anlamsız
  ".p12"
  ".mobileprovision"
  ".cer"

  # Git internals
  ".git/"

  # Kit dosyaları — proje içinden değiştirilmemeli
  ".claude-kit/core/"
)

for pattern in "${PROTECTED_PATTERNS[@]}"; do
  if [[ "$FILE_PATH" == *"$pattern"* ]]; then
    echo "Blocked: '$FILE_PATH' is a protected file (matched '$pattern'). Do not edit this file." >&2
    exit 2
  fi
done

exit 0
